server:
  port: 18080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/curi?currentSchema=curi_admin
    username: curi
    password: curi123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    properties.hibernate:
      format_sql: true
      use_sql_comment: true
    generate-ddl: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: true
  url:
    base: http://localhost:18080
  redis:
    host: localhost
    port: 6379
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: info
    com:
      example:
        basic:
          local: debug
          global: debug
    org:
      hibernate:
        type:
          descriptor:
            sql: trace