server:
  port: 18090
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate:
      format_sql: true
      use_sql_comment: true
    generate-ddl: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
#  url:
#    base: http://localhost:18090
  redis:
    host: localhost
    port: 6379
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  security:
    user:
      name: user
      password: test
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: foo
          client-secret: bar
#        authorization:
#          check-token-access: isAuthenticated()

logging:
  level:
    root: info
    com:
      example:
        basic:
          local: debug
          global: debug
    org:
      hibernate:
        type:
          descriptor:
            sql: trace